---
- hosts: myke
  remote_user: root
  vars:
    remote_app_root: /var/www/html/connectfour/
    artifact: app.tar
  tasks:
    - name: Build project 
      command: ng build --prod --base-href=https://connectfour.codecritique.org
      delegate_to: 127.0.0.1
    - name: Create distribution artifact {{ artifact }}
      command: tar -cvf ../app.tar .
        chdir=dist
      delegate_to: 127.0.0.1
    - name: Delete remote deploy directory 
      file:
        path: '{{ remote_app_root }}'
        state: absent
    - name: Create new remote deploy directory {{ remote_app_root }}
      file:
        path: '{{ remote_app_root }}'
        state: directory
    - name: Unpack {{ artifact }} into remote directory {{ remote_app_root }}
      unarchive:
        src: '{{ artifact }}'
        dest: '{{ remote_app_root }}'
    - name: Delete {{ artifact }}
      file:
        path: '{{ artifact }}'
        state: absent
      delegate_to: 127.0.0.1
...
